#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const src=fs.readFileSync(path.join(root,'jinpo-ai-chat.js'),'utf8');
let pass=0,fail=0;
function check(name,cond,detail){if(cond){pass++;return;}fail++;console.error('FAIL:',name,detail||'');}
check('normalize response preserves structured data',/data\s*:\s*data\.data\s*&&\s*typeof data\.data===['"]object['"]\s*\?\s*data\.data\s*:\s*null/.test(src));
check('conversation repair metadata stored',/conversationRepair\s*:\s*true[\s\S]{0,600}repairTargetDomain/.test(src));
check('conversation repair preserved query stored',/preservedQuery\s*:\s*String\(result\.data\.preservedQuery/.test(src));
check('hero refinement metadata stored',/heroRefinement\s*:\s*result\.data\.heroRefinement\s*\|\|\s*null/.test(src));
check('site condition metadata stored',/siteConditions\s*:\s*Array\.isArray\(result\.data\.siteConditions\)/.test(src));
check('known term guidance marker stored',/knownTermGuidance\s*:\s*!!result\.data\.knownTermGuidance/.test(src));
check('known term key stored',/termKey\s*:\s*String\(result\.data\.termKey/.test(src));
check('known term normalized value stored',/normalizedTerm\s*:\s*String\(result\.data\.normalizedTerm/.test(src));
check('known term approximate marker stored',/approximateTerm\s*:\s*!!result\.data\.approximateTerm/.test(src));
check('vague capability kind stored',/siteVagueCapability\s*:\s*String\(result\.data\.siteVagueCapability/.test(src));
check('vague capability clarification stored',/siteVagueCapabilityClarification\s*:\s*!!result\.data\.siteVagueCapabilityClarification/.test(src));
check('vague capability followup stored',/siteVagueCapabilityFollowup\s*:\s*!!result\.data\.siteVagueCapabilityFollowup/.test(src));
check('vague capability revision stored',/siteVagueCapabilityRevision\s*:\s*!!result\.data\.siteVagueCapabilityRevision/.test(src));
check('site guide context clear stored',/siteGuideContextCleared\s*:\s*!!result\.data\.siteGuideContextCleared/.test(src));
check('previous selected site item stored',/previousSelectedSiteItem\s*:\s*String\(result\.data\.previousSelectedSiteItem/.test(src));
check('link miss recovery stored',/siteLinkMissRecovery\s*:\s*!!result\.data\.siteLinkMissRecovery/.test(src));
check('link miss rejected item stored',/siteLinkMissRejectedItem\s*:\s*String\(result\.data\.siteLinkMissRejectedItem/.test(src));
check('link miss selection resolution stored',/siteLinkMissSelectionResolved\s*:\s*!!result\.data\.siteLinkMissSelectionResolved/.test(src));
check('link miss recovery continuation stored',/siteLinkMissRecoveryContinuation\s*:\s*!!result\.data\.siteLinkMissRecoveryContinuation/.test(src));
check('guide pause turn count stored',/siteGuidePauseTurns\s*:\s*Number\(result\.data\.siteGuidePauseTurns/.test(src));
check('guide return with goal stored',/siteGuideReturnWithGoal\s*:\s*!!result\.data\.siteGuideReturnWithGoal/.test(src));
check('guide return target stored',/siteGuideReturnTarget\s*:\s*String\(result\.data\.siteGuideReturnTarget/.test(src));
check('inline goal revision stored',/siteInlineGoalRevision\s*:\s*!!result\.data\.siteInlineGoalRevision/.test(src));
check('known term clarification marker stored',/knownTermClarification\s*:\s*true/.test(src));
check('known term clarification reason stored',/clarificationReason\s*:\s*String\(result\.data\.clarificationReason\|\|result\.data\.reason/.test(src));
check('known term clarification pending hero stored',/pendingHero\s*:\s*String\(result\.data\.pendingHero/.test(src));
check('jinpo continuation marker stored',/jinpoContinuation\s*:\s*true/.test(src));
check('jinpo continuation site item stored',/siteItem\s*:\s*['"]jinpo['"]/.test(src));
check('jinpo continuation resolution reason stored',/resolutionReason\s*:\s*String\(result\.data\.context\.reason/.test(src));
check('jinpo continuation context message stored',/contextMessage\s*:\s*String\(result\.data\.context\.message/.test(src));
check('site guide continuation context message stored',/contextMessage\s*:\s*String\(result\.data\.context&&result\.data\.context\.message/.test(src));
check('hero cost continuation metadata stored',/cost\s*:\s*Number\(result\.data\.cost\|\|result\.data\.filters&&result\.data\.filters\.cost\)/.test(src));
check('hero ranking continuation metadata stored',/ranking\s*:\s*!!result\.data\.ranking/.test(src)&&/low\s*:\s*!!result\.data\.low/.test(src));
check('partial specified search continuation stored',/specified_search_partial/.test(src));
check('large history metadata is pruned',/function pruneHistoryMetadata\s*\(/.test(src)&&/heroRefinement/.test(src)&&/3500000/.test(src));
console.log(`CHAT HISTORY METADATA: ${pass} / ${pass+fail} PASS`);
if(fail)process.exit(1);
